package com.gang.exception;

public class ExceptionMain {

	public static void main(String[] args) {
		System.out.println("메인 시작");
		Test test = new Test();
		//test.t1();
		System.out.println("메인 종료");
		test.t2();

		
	}

}
